[workspace]
members = [ "b_vk","jester", "jester_core"]

[workspace.dependencies]
ash = "0.38.0"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
winit = "0.30.11"
image = "0.25.6"
bytemuck = "1.23.1"
glam = "0.30.4"
hashbrown = "0.15.4"
