[package]
name = "jester_core"
version = "0.1.0"
edition = "2024"

[dependencies]
ash.workspace = true
bytemuck.workspace = true
thiserror = "2.0.12"
tracing.workspace = true
tracing-subscriber.workspace = true
winit.workspace = true
image.workspace = true
glam.workspace = true
